### ISSUE TITLE
Consider adding sentence analysis functionality to TurkishMorphology.

### ISSUE THREAD

**Issue by ahmetaa** [ahmetaa/zemberek-nlp#100]

**Comment by mdakin** [comment]
From disambiguation perspective, I think morphological analysis always benefit from more context right?

**Comment by ahmetaa** [comment]
There is already a TurkishSentenceAnalyzer class. Which is instantiated with a TurkishMorphology object and a Disambiguator. However, TurkishMorphology is already behaving like a facade class (This is related with #96 ). So it may be a better idea to put sentenceanalysis functionality there. 

Now:

```
TurkishMorphology morphology = TurkishMorphology.createWithDefaults();
TurkishMorphDisambiguator disambiguator = new Z3MarkovModelDisambiguator();
TurkishSentenceAnalyzer analyzer = new TurkishSentenceAnalyzer(morphology, disambiguator);
SentenceAnalysis result = analyzer.analyze("Merhaba Dünya.");
analyzer.disambiguate(result); 
// or to directly get the best result
List<WordAnalysis> analyzer bestParse(String sentence) 
```

Then:
```

TurkishMorphology morphology = TurkishMorphology.createWithDefaults();
SentenceAnalysis result = morphology.analyzeSentence("Merhaba Dünya.");
morphology.disambiguate(result); 
```

TurkishSentenceAnalyzer api is also a little confusing but that is another issue.

**Comment by mdakin** [comment]
Sounds good.

**Comment by ahmetaa** [comment]
0.12.0 adresses this.
