### ISSUE TITLE
Avoid main methods in library classes

### ISSUE THREAD

**Issue by mdakin** [ahmetaa/zemberek-nlp#116]
They are quite handy for quick testing, but in most cases there should be a separate class to test the functionality with preferably command line parameters for input/output files this would avoid user dependent or hardcoded directories in the codebase as well. In some cases unit tests are enough anyway.

**Comment by mdakin** [comment]
There are currently 23 main methods in the project.

https://github.com/ahmetaa/zemberek-nlp/search?utf8=%E2%9C%93&q=%22void+main%22&type=Code

**Comment by ahmetaa** [comment]
Agreed. This is an easy fix.

**Comment by ahmetaa** [comment]
This is addressed (mostly) in 0.12.0 closing it for now.
