### ISSUE TITLE
How can we use this? I am a C# developer

### ISSUE THREAD

**Issue by MonsterMMORPG** [ahmetaa/zemberek-nlp#119]
I have downloaded the application

Opened the project inside intelliJS

Here : 

![asdasasdas](https://cloud.githubusercontent.com/assets/4149474/23773271/7f9c6b9c-052f-11e7-9913-686cd4f3f1e0.png)

Then what do i do? What i want is a simple task

I want to provide the word and get what is is

For example for the word "çalışmışım" i would like to learn it is a verb and it is Past Dubitative first person singular

Or for example "evler" is plural of noun "ev" etc

However i have no idea how can i do it? Any help and tutorial is appreciated 

If there were a command line version that would be great

Like i can call via command line and write output to a file

That way i can use it in my c# application directly

**Comment by ahmetaa** [comment]
For using from a C# application, a good way is to make a small server application in Java. 
A command line console is also possible but it is not available yet.
