### ISSUE TITLE
Where can we learn what does these tags mean? 

### ISSUE THREAD

**Issue by MonsterMMORPG** [ahmetaa/zemberek-nlp#120]
First : is this project uses latest files? dictionaries etc? https://github.com/ahmetaa/turkish-nlp-examples

Because it is the only project i have managed the work

And here the other questions based on below examples and outputs

Why word koşar has 3 results? What does each one mean?
What does mean Aor?
What does this mean? (Verb;Pos)(Adj;AorPart:ar) : it is verb or adjective?
What does mean Prop? A3sg? Pnon? Nom?
What does mean Narr?

So basically i need a detailed documentation about each possible case

Thank you

Few examples

```
Word = dekorasyonumuzla
[(dekorasyon:dekorasyon) (Noun;A3sg+P1pl:umuz+Inst:la)]

Word = koşar
[(koşmak:koş) (Verb;Pos+Aor:ar+A3sg)]
[(koşmak:koş) (Verb;Pos)(Adj;AorPart:ar)]
[(Koşar:koşar) (Noun,Prop;A3sg+Pnon+Nom)]

Word = giderlermiş
[(gitmek:gid) (Verb;Pos+Aor:er+A3pl:ler+Narr:miş+A3sg)]
[(gider:gider) (Noun;A3pl:ler+Pnon+Nom)(Verb;Narr:miş+A3sg)]
[(gitmek:gid) (Verb;Pos)(Adj;AorPart:er)(Noun;A3pl:ler+Pnon+Nom)(Verb;Narr:miş+A3sg)]

Word = Ahmetler
[(Ahmet:ahmet) (Noun,Prop;A3pl:ler+Pnon+Nom)]
[(Ahmetler:ahmetler) (Noun,Prop;A3sg+Pnon+Nom)]

Word = olmayansaçmakelimegrubu
[(UNK:olmayansaçmakelimegrubu) (Unk,Unk;Unkown)]

Word = dekorasyonumuzla
[(dekorasyon:dekorasyon) (Noun;A3sg+P1pl:umuz+Inst:la)]

Word = kantindeydik
[(kantin:kantin) (Noun;A3sg+Pnon+Loc:de)(Verb;Past:ydi+A1pl:k)]

Word = genelleştirileceğine
[(genel:genel) (Adj)(Verb;Become:leş)(Verb;Caus:tir)(Verb;Pass:il+Pos)(Noun;FutPart:eceğ+A3sg+P3sg:i+Dat:ne)]
[(genel:genel) (Adj)(Verb;Become:leş)(Verb;Caus:tir)(Verb;Pass:il+Pos)(Noun;FutPart:eceğ+A3sg+P2sg:in+Dat:e)]

Word = Nazım'ımız
[(nâzım:nazım) (Noun;A3sg+P1pl:ımız+Nom)]
[(nâzım:nazım) (Adj)(Noun;A3sg+P1pl:ımız+Nom)]

Word = Nazımımız
[(nâzım:nazım) (Noun;A3sg+P1pl:ımız+Nom)]
[(nâzım:nazım) (Adj)(Noun;A3sg+P1pl:ımız+Nom)]
```

**Comment by ahmetaa** [comment]
These are morpheme names (Suffix for Turkish). You can find some explanation in here: 

https://docs.google.com/document/d/1bUW6i5KrjkeID8GD7rs8tbGWapZooLmt2gmdAUvPHW8/edit?usp=sharing

Turkish is highly ambigious, therefore there can always be multiple analysis results for words. Also, because library is not yet stable, there can be bugs and wrong results.
