### ISSUE TITLE
Can we obtain synsets, synonyms, antonyms etc like in English WordNet?

### ISSUE THREAD

**Issue by MonsterMMORPG** [ahmetaa/zemberek-nlp#121]
In English wordnet we can obtain many relations

Here the link : https://wordnet.princeton.edu/

I wonder such thing is possible in zemberek?

Like obtaining synsets of a word or synonyms, antonyms  etc

**Comment by ahmetaa** [comment]
Zemberek does not provide wordnet capabilities yet. However, there is a wordnet available for Turkish (it is quite old though.): https://bitbucket.org/ozlemc/twn/downloads/
Please note that this files are in public domain but I do not know the license of it.
