### ISSUE TITLE
"arabalar" analyze error.

### ISSUE THREAD

**Issue by ahmetaa** [ahmetaa/zemberek-nlp#123]
Gives wrong analysis:
[(arap:arab) (Noun;A3sg+Pnon+Dat:a)(Verb;Pres+A3pl:lar)]

**Comment by mugesevinc** [comment]
It is not ok to follow the nouns ,which take dative (-a/-e) and acc(-i) case,  with plural suffix  (Verb;Pres+A3pl:lar)]:
Ex:
*eveler
*kapıyalar
*orduyalar

*eviler (only poss:i is possible)
*kapıyılar
*orduyular
