### ISSUE TITLE
Failed to analyze words list (15k) out of 1.3m words

### ISSUE THREAD

**Issue by MonsterMMORPG** [ahmetaa/zemberek-nlp#124]
I have generated 1.3m words by using latest spell checker dictionary files

Attached the list of failed to analyze and all words list

[fails.txt](https://github.com/ahmetaa/zemberek-nlp/files/834995/fails.txt)
[allWordsSuffixes.txt](https://github.com/ahmetaa/zemberek-nlp/files/834997/allWordsSuffixes.txt)

**Comment by ahmetaa** [comment]
Where did you get the spell checker dictionary files?

**Comment by MonsterMMORPG** [comment]
@ahmetaa it can be downloaded from here : https://addons.mozilla.org/en-US/firefox/addon/t%C3%BCrk%C3%A7e-imla-denetimi/?src=search

**Comment by ahmetaa** [comment]
Thanks. I will have a look and add missing roots and fix suffix issues as much as possible. 
There are also a lot of incorrect words in the fail list.

**Comment by MonsterMMORPG** [comment]
Yes i also have noticed there are incorrect words. Thank you.

**Comment by ahmetaa** [comment]
Fixed 2057 of them.

**Comment by ahmetaa** [comment]
I will close this issue as morphology module is re-written. Please do file issues for single or group of words that are failed to get analyzed.
