### ISSUE TITLE
Should parse "yapacağa"

### ISSUE THREAD

**Issue by ahmetaa** [ahmetaa/zemberek-nlp#126]
For usages like "yapacağa benziyor"
However, I am not sure if it ends with a Dative suffix.

**Comment by mugesevinc** [comment]
yapacağa:
(Verb:yap+Pos)(Adj+FutPart:acak)(Noun+..+Dat:a)

**Comment by ahmetaa** [comment]
Thanks @mugesevinc 
This is fixed in 0.12.0. Closing.
