### ISSUE TITLE
zemberek-parsed-words-min10.txt is missing

### ISSUE THREAD

**Issue by alisafaya** [ahmetaa/zemberek-nlp#127]
Hi !
Firstly i want to thank you for these huge efforts .
I've downloaded the repository and tried to build it but i faced the error said that "zemberek-parsed-words-min10.txt" named text file cannot be found .
I researched repository but i could not find it unfortunately .
the file is used at the class " normalization.TurkishSpellChecker "

`List<String> vocab = Files.readAllLines(
                new File(Resources.getResource("zemberek-parsed-words-min10.txt").getFile()).toPath());`

**Comment by ahmetaa** [comment]
Zemberek spell checker work is still experimental unfortunately. That file is rather large (even if it is much smaller than the original list). I will put here (  https://drive.google.com/open?id=0B9TrB39LQKZWc0c5Q0V3MU9pSms ) for you to test the functionality. Keep in mind that I am working on that area now, classes and files will change. Probably that file will not be used at all.
