### ISSUE TITLE
Change names of classes TurkishLexer and ZemberekLexer

### ISSUE THREAD

**Issue by ahmetaa** [ahmetaa/zemberek-nlp#128]
This will be a breaking change. 
Motivation: NLP systems usually use the word "Tokenizer" instead of "Lexer". Also, users may be confused which class to use now. 
Proposal:
TurkishLexer -> AntlrTurkishLexer // this is the low level lexer auto generated by Anltr
ZemberekLexer->TurkishTokenizer // this is the high level user facing tokenizer.

Alternatively, in case there will be another tokenizer implementation:

ZemberekLexer->RuleBasedTurkishTokenizer 

but perhaps for simplicity TurkishTokenizer is better.

**Comment by ahmetaa** [comment]
@mdakin

**Comment by mdakin** [comment]
Sounds good, ship it.
