### ISSUE TITLE
Units of measurement: km and cm

### ISSUE THREAD

**Issue by kokeksibir** [ahmetaa/zemberek-nlp#129]
Not sure if it is a necessity but I think there may be something in units of measurement. The first results for single word morphological analysis of **km** and **cm** are as follows

- [(K:k) (Noun,Prop;A3sg+P1sg:m+Nom)]
- [(C:c) (Noun,Prop;A3sg+P1sg:m+Nom)]

**Comment by ahmetaa** [comment]
Thanks, 
Yes, this is a known issue. We will likely to limit the morphotactics for Abbreviations and letters etc. (Not allowing possessive suffixes for most of them). But this may happen in V0.12.0.

**Comment by kokeksibir** [comment]
Thanks, please keep this great work 🥇

**Comment by ahmetaa** [comment]
This is fixed in 0.14.0. Abbreviations are no longer accepting possessive suffixes.
