### ISSUE TITLE
StemNode in lexicon.graph could be nimbler

### ISSUE THREAD

**Issue by mdakin** [ahmetaa/zemberek-nlp#130]
Looks like each StemNode contains  a DictionaryItem object and each Dictionary contains an Exclusive Suffix data object among others: 

```
public class ExclusiveSuffixData {
    public SuffixData accepts = new SuffixData();
    public SuffixData rejects = new SuffixData();
    public SuffixData onlyAccepts = new SuffixData();
..

```

SuffixData object has a HashSet and a BitSet, these could contain 0-100 elements, and 0 elements is quite common.

The very first thing that can be done is, not to create the Sets during object creation but only if SuffixData has more than 0 elements.

**Comment by ahmetaa** [comment]
These classes are retired in 0.12.0. Closing.
