### ISSUE TITLE
Language Identifier results

### ISSUE THREAD

**Issue by alisafaya** [ahmetaa/zemberek-nlp#132]
`LangId = LanguageIdentifier.fromInternalModelGroup("tr_group");`
`LangId.containsLanguage("ahmet","tr",10);`
`LangId.containsLanguage("kitap","tr",10);`
these two returned `false` .
how can i detect Turkish words from other languages' words ?
i am doing morphological analysis over wikipedia's turkish version, and i want to get rid of non-Turkish words .

**Comment by ahmetaa** [comment]
Language identification mechanism is designed for detecting language of sentences, paragraphs or documents not individual words. Usually you need >20 characters of words to have good results. If you want to eliminate non Turkish words, perhaps it is better to use the morphological analysis mechanism.  However in that case some proper nouns that does not exist in Zemberek root dictionary will be also be eliminated.

**Comment by ahmetaa** [comment]
Also if you explain what do you want to achieve by eliminating Turkish words we may have suggestions.

**Comment by alisafaya** [comment]
of course, I want to train word2vec model using turkish version of wikipedia .

**Comment by ahmetaa** [comment]
Then I suggest not eliminating non Turkish words. There will not be much adverse effects of foreign words that occurred in Wikipedia. If problem is sparsity (eg. too much words) then apply lemmatization. Also, Fasttext may be more suitable for languages like Turkish. Lastly, Fasttext already provides pre-trained vectors for Turkish. 

https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

**Comment by alisafaya** [comment]
Thanks for your interest .
