### ISSUE TITLE
Cümle Analizi

### ISSUE THREAD

**Issue by hasnhasan** [ahmetaa/zemberek-nlp#133]
Bu projede cümle analizi yapabiliyor muyuz acaba ?
Bir cümlenin öznesini yüklemini bulabiliyor mu ?

**Comment by ahmetaa** [comment]
Geç cevap için kusura bakmayın. Hayır, henüz bu özellik yok. Dependency Parsing ile bu -belli derecede- yapılabiliyor.

**Comment by hasnhasan** [comment]
Estağfrullah. Cevabınız için teşekkürler. Bununla ilgili bir çalışma yaparsam size bildiririm.

İyi çalışmalar.
