### ISSUE TITLE
Example Dictionary Format

### ISSUE THREAD

**Issue by memduhcagridemir** [ahmetaa/zemberek-nlp#134]
Hello,

We need to use a custom dictionary in addition to default dictionaries for morphological analysis tasks. 

According to page at https://github.com/ahmetaa/zemberek-nlp/tree/master/morphology we should be able to add custom dictionaries. But the rules of custom dictionaries are left blank. 

Is there any document we can read to understand the rules? Could you provide an example of dictionary rules so that we can format our dictionary?

Thank you

**Comment by ahmetaa** [comment]
That is correct. We have not yet prepared documentation for dictionary rules. However, in the mean time you can check here for some examples (it does not cover all use cases): 
https://github.com/ahmetaa/zemberek-nlp/blob/master/morphology/src/test/resources/dev-lexicon.txt
I will leave this issue open until documentation is added.

**Comment by mdakin** [comment]
Dictionary rules are explained here:
https://github.com/ahmetaa/zemberek-nlp/wiki/Text-Dictionary-Rules

**Comment by ahmetaa** [comment]
Sayfayı güncelledim.
