### ISSUE TITLE
Turkish Spell Checker Windows 10 Illegal char hatası

### ISSUE THREAD

**Issue by plxCrush** [ahmetaa/zemberek-nlp#151]
Merhabalar kelime öneri sistemini kullandığımda böyle bir hata alıyorum. Nedeni ne olabilir ve nasıl düzeltilebilir?

java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\C:\Users\plx\.m2\repository\zemberek-nlp\normalization\0.11.0\normalization-0.11.0.jar!\endings
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.io.File.toPath(Unknown Source)
	at zemberek.normalization.StemEndingGraph.<init>(StemEndingGraph.java:34)
	at zemberek.normalization.TurkishSpellChecker.<init>(TurkishSpellChecker.java:33)
	at WordCorrector.correct(WordCorrector.java:9)
	at Main.main(Main.java:77)

**Comment by alisafaya** [comment]
Excuse me, Could you solve this issue, if you could how did you solve it ?

**Comment by ahmetaa** [comment]
I did not look at the issue since it was closed. I will check it out if this is still an issue.

**Comment by alisafaya** [comment]
I've just figured out that my bug is not an " illegal char " bug, but the file endings couldn't be found ( I am getting NoSuchFileException ) although the file exists and I can open it in the IDE

**Comment by ahmetaa** [comment]
Ok, will check.

**Comment by alisafaya** [comment]
Thanks for your interest

**Comment by koust** [comment]
I'm getting the same error

**Comment by ahmetaa** [comment]
I fix this issue in the trunk, a new release is required. I am in the middle of a big re-write but will try a new release this weekend.

**Comment by plxCrush** [comment]
Sorry for late response, SpellChecker works fine on both MAC & Linux. I had this problem on win10. On win10 manual import of zemberek jar files solves this issue but it wasn't working for me with pom.xml import.

**Comment by plxCrush** [comment]
I checked this on win 10 again few minutes ago. Seems working fine with maven import too. Guess you fixed it.
