### ISSUE TITLE
getLemmas() hatası

### ISSUE THREAD

**Issue by aucan** [ahmetaa/zemberek-nlp#152]
"bırakılamaz" kelimesi için getLemmas() yordamını debug modda çağırdığımda dönüş listesi içerisinde 3 eleman gelmekteyken, normal çağırdığımda ise dönüş listesi içerisinde 4 eleman geliyor. Acaba sorun ne olabilir. 

```
WordAnalysis result = morphology.analyze("bırakılamaz").get(0);
	List<String> lemmas = result.getLemmas();
	for (String lm : lemmas) {
		System.out.println(lm);
	}
```

**Comment by ahmetaa** [comment]
Şu anda morfolojik analiz modülünde büyükçe bir yeniden yazma denemesi yapıyoruz. Bu süre içinde su andaki modüle ait problemler ile ilgilenmeye zamanım olmayacak. Umuyorum daha iyi bir sistem olacak ve bu problem de çözülecek.

**Comment by ahmetaa** [comment]
Bunun 0.12.0 ile çözüldüğünü düşünüyorum. Aksi durumda tekrar açabilirsiniz.
