### ISSUE TITLE
About server

### ISSUE THREAD

**Issue by koust** [ahmetaa/zemberek-nlp#155]
I want to use the zemberek library quickly. What should be minimum server features?

My server features:
1 Cpu and 1 GB Ram hosted by digital ocean.

Note: Load time average 7-8s.

**Comment by ahmetaa** [comment]
Please hang on for about one or two weeks, I will provide this information in the next version because there will be several internal changes.

**Comment by ahmetaa** [comment]
But current version probably works okay with that configuration depending on usage scenario.

**Comment by koust** [comment]
I understand. you think, it possible to get by with this performance feature and good configuration?

**Comment by mdakin** [comment]
Yeni versiyonun bellek kullanim ve performans karakteristikleri farkli olacak, serverin ayaga kalkis suresi su anda orta karar bir bilgisayarda ~1-2 sn civari olmasi lazim. Sunucu ayaga kalktiktan sonra saniyede onbinlerce kelimeyi cozumleyebilir.

Yakinda daha kapsamli bir server versiyonu yazmayi dusunuyorum. Izlemek istersen surada: https://github.com/mdakin/zemberek-io
