### ISSUE TITLE
Filleri,kökü,ekleri ayrı ayrı almak

### ISSUE THREAD

**Issue by timucincicek** [ahmetaa/zemberek-nlp#159]
Word analysis classının metotlarını kullanarak kökü getRoot() metodu ile alabiliyoruz.Lakin fiili,zarfı,sıfatı,ekleri de alabileceğimiz metotlar var mıdır?

**Comment by mdakin** [comment]
@timucincicek 

Su ornekleri inceleyebilirsin:
https://github.com/ahmetaa/zemberek-nlp/blob/master/examples/src/main/java/zemberek/examples/morphology/AnalyzeWords.java

https://github.com/ahmetaa/zemberek-nlp/blob/master/examples/src/main/java/zemberek/examples/morphology/DisambiguateSentences.java
