### ISSUE TITLE
Failing tests in morphology

### ISSUE THREAD

**Issue by abdelrahman-t** [ahmetaa/zemberek-nlp#163]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] zemberek-nlp ....................................... SUCCESS [01:53 min]
[INFO] zemberek-core ...................................... SUCCESS [  8.405 s]
[INFO] zemberek-tokenization .............................. SUCCESS [  2.941 s]
[INFO] zemberek-lm ........................................ SUCCESS [  0.197 s]
[INFO] zemberek-lang-id ................................... SUCCESS [  0.538 s]
[INFO] zemberek-morphology ................................ FAILURE [01:05 min]
[INFO] zemberek-normalization ............................. SKIPPED
[INFO] zemberek-classification ............................ SKIPPED
[INFO] zemberek-apps ...................................... SKIPPED
[INFO] zemberek-ner ....................................... SKIPPED
[INFO] zemberek-grpc-server ............................... SKIPPED
[INFO] zemberek-all ....................................... SKIPPED
[INFO] zemberek-experiment ................................ SKIPPED
[INFO] zemberek-examples .................................. SKIPPED

Failed tests: 
  InformalTurkishAnalysisTest.testProgressiveDeformation2:49 Anaysis Failed for [okuyom]. Predicate Input = Verb + Prog1 + A1sg
  InformalTurkishAnalysisTest.testProgressiveDeformation:24 Anaysis Failed for [yazıyom]. Predicate Input = Verb + Prog1 + A1sg
  InformalTurkishAnalysisTest.optativeP1plDeformation:101 Anaysis Failed for [yazak]. Predicate Input = Verb + Opt + A1pl
  InformalTurkishAnalysisTest.futureDeformation:113 Anaysis Failed for [yazacam]. Predicate Input = Verb + Fut + A1sg
  InformalTurkishAnalysisTest.progressiveDeformationNegative:82 Anaysis Failed for [yazmıyom]. Predicate Input = Verb + Neg + Prog1 + A1sg
  InformalTurkishAnalysisTest.progressiveDeformationDrop:58 Anaysis Failed for [arıyom]. Predicate Input = Verb + Prog1 + A1sg

Tests run: 195, Failures: 6, Errors: 0, Skipped: 7

**Comment by abdelrahman-t** [comment]
Build successeds when going back to 725afd24ab79bec2e092b7edf6af0063771c3734.

**Comment by ahmetaa** [comment]
Thanks. Fixed in 8608243
