### ISSUE TITLE
text classification scores

### ISSUE THREAD

**Issue by crayzsociety** [ahmetaa/zemberek-nlp#165]
hi,
what does  means the scores below. actually I wonder about how can we convert this scores to percentage values?

__label__spor: 0.000010
__label__türki to: -11.483298
__label__ Tuesday: -11.512561

**Comment by ahmetaa** [comment]
Numbers are the result of softmax function.  They are natural logarithm values of probabilities if I am not mistaken. Just calculate exp(value) to convert actual probabilities.

**Comment by crayzsociety** [comment]
actualyy there exitsts a function doing this in Model.java(computeOutputSoftmax).but still we getting results like -7,-4

**Comment by ahmetaa** [comment]
Have you tried Math.exp(value) ?
