### ISSUE TITLE
currently supported morphemes for word generation

### ISSUE THREAD

**Issue by abdelrahman-t** [ahmetaa/zemberek-nlp#166]
Can all of the morphemes at https://github.com/ahmetaa/zemberek-nlp/wiki/Morphemes be used for word generation? is there a list of the currently supported ones?

thanks, 

this is a very well written library btw, keep up the great work!

**Comment by ahmetaa** [comment]
Thanks. And, Yes you can use all morphemes. However we did not test generation mechanism well. Please submit an issue if you find a problem.
