### ISSUE TITLE
Redundant Adj -> Noun -> Noun conversion

### ISSUE THREAD

**Issue by ahmetaa** [ahmetaa/zemberek-nlp#167]
For input "kopukluk"

[kopuk:Adj] kopuk:Adj|luk:Ness→Noun+A3sg
[kopuk:Adj] kopuk:Adj|Zero→Noun+A3sg|luk:Ness→Noun+A3sg

Second analysis should not be offered.

(Via Müge)

**Comment by ademozgur87** [comment]
Merhaba,

"Özgür bugün çok yoruldu" cümlesinde "Özgür" kelimesi isim yerine sıfat olarak çözümleniyor.

**Comment by ahmetaa** [comment]
@ademozgur87 bunun için yeni bir issue açarsanız sevinirim. Ama şunu diyebilirim, aslında özel ad olan Ögzür'ün de çözümlemesi var. Belirsizlik giderici hata yapıyor sadece. Belirsizlik giderici henüz çok yüksek başarı ile çalışmadığı için hata yapacaktır.

Şu şekilde:

Özgür
[özgür:Adj] özgür:Adj*
[Özgür:Noun,Prop] özgür:Noun+A3sg
bugün
[bugün:Adv] bugün:Adv
[bugün:Noun,Time] bugün:Noun+A3sg*
çok
[çok:Adj] çok:Adj
[çok:Adv] çok:Adv*
[çok:Det] çok:Det
[çok:Postp,PCAbl] çok:Postp
yoruldu
[yormak:Verb] yor:Verb|ul:Pass→Verb+du:Past+A3sg
