### ISSUE TITLE
Exceeded 32bits when ngram count * blocksize is bigger than Integer.MAX_VALUE (#2)

### ISSUE THREAD

**Issue by bojie** [ahmetaa/zemberek-nlp#177]
Hi Ahmetaa,

Thanks for the quick fix of #176

From my test, "while (l < count * blockSize)" would be changed to "while (l < (long)count * blockSize)", because "count * blockSize" will be less than 0.

Also "total" would be changed to long too, otherwise it becomes negative too.

Here are the values I printed from my generated LM, with #176 patch
pageCounter=0
count*blockSize=-1829857156
total=-2147483648

My LM information：
Gram counts in Arpa file: 795424 387938403 616498925 670859407 432548210
chunkBits = 21
fingerPrintBits = 16
probabilityBits = 8
backoffBits = 8
fractionDigits = 4
2 grams segment count = 256, Avrg segment size = 2097152
3 grams segment count = 512, Avrg segment size = 2097152  
4 grams segment count = 512, Avrg segment size = 2097152  
5 grams segment count = 256, Avrg segment size = 2097152  

Br
Bojie

**Comment by ahmetaa** [comment]
Thanks again. There may be more places to check for this issues. I will provide a patch and perhaps a functional test for this.

**Comment by ahmetaa** [comment]
I decided not to add a functional test for now because of the time constraints. Closing. Please let me know if you could manage generating the model.
