### ISSUE TITLE
Double Quotation Mark and sentences detections

### ISSUE THREAD

**Issue by gokhanakgul** [ahmetaa/zemberek-nlp#192]
Hi ,

I was testing your first sample in Turkish Sentence Extraction.
I attached my sample text file . I figure out sentence extraction issue if a sentence starts with double quotation mark  and including a punctuation like ( .  !  ...) sentence ends without closing double quotation included. 

I extracted following sentences from attached text .

`
Ay hep beraber yaşadıkları mağaranın ağzında parladı.
--------------------------------------
"Arrh!
--------------------------------------
" dedi Baba Kurt.
` 
How can I correctly extarct the text as following.

`
Ay hep beraber yaşadıkları mağaranın ağzında parladı.
--------------------------------------
"Arrh!"
--------------------------------------
dedi Baba Kurt.
` 
 
Best Regards

[rudyard.txt](https://github.com/ahmetaa/zemberek-nlp/files/2568426/rudyard.txt)

**Comment by ahmetaa** [comment]
This is a known issue. Sentence boundary detection with narration is not an easy task.Perhaps some improvement can be made for simple cases like the example you gave. but for example what would a human do for a case like:

Sonra "Merhaba! Bugün hava çok güzel. " diye ekledi adam.

**Comment by ahmetaa** [comment]
We actually tried that technique before (tokenization before segmentation). But I prefer the current method better. 
I will consider this issue. Perhaps adding a configuration parameter to the TurkishSentenceExtractor that allows ignoring processing text in double quotes may give users some flexibility.  No promises though.

**Comment by gokhanakgul** [comment]
Thank you so much.

**Comment by teaddict** [comment]
I have same problem with this : 
`Ünlü yazar CS Lewis, “Ne! Sen de mi? Bir tek benim sanıyordum dediğimiz anda başlar arkadaşlık” diyordu.` 

It creates 3 sentences:
`Ünlü yazar CS Lewis, “Ne!`
`Sen de mi?`
`Bir tek benim sanıyordum dediğimiz anda başlar arkadaşlık,” diyordu.`

**Comment by ahmetaa** [comment]
You can review https://github.com/ahmetaa/zemberek-nlp/commit/cf3789bc65f780fce89b9b81165d3c5f08218d1b if you have time. This may not be suitable sor some cases. But at least there is an option now.

**Comment by ahmetaa** [comment]
I am marking this a closed.
