### ISSUE TITLE
Add ambiguityResolver to TurkishMorphology constructor

### ISSUE THREAD

**Issue by yusufcakmakk** [ahmetaa/zemberek-nlp#194]
Hi all,

I realized that when I use ambiguity model from different path, builder does not set it. So I add 
`this.ambiguityResolver = builder.ambiguityResolver;`
to TurkishMorphology constructor.

I hope it works for you and other developers .

Thank you so much for all your work.

**Comment by ahmetaa** [comment]
Thanks for the catch. I think https://github.com/ahmetaa/zemberek-nlp/commit/8cfb661034d55c84f07457eaa51bb504f6c64217 fixes it.
