### ISSUE TITLE
Sözlükte arama

### ISSUE THREAD

**Issue by nexaas** [ahmetaa/zemberek-nlp#195]
merhaba, fikir danışmak adına bir sorum olacak.
elimizde bir osmanlıca sözlük var bu sözlükteki terimler bir veya birden fazla kelimelerden oluşuyor("NUFUS HUVIYET CUZDANI","NUTUKHAN","MUHAKEME".....gibi)
arama motorumuza yazılan bir cümlede geçen ve sözlükte mevcut olan terimleri bulup anlamlarını göstermek istiyoruz.NLP'de bu problem ne olarak geçiyor veya projenizde bununla ilgili bir çalışma var mıdır,tavsiyenizi bizimle paylaşır mısınız ?

**Comment by ahmetaa** [comment]
Bu uygulamaya özel bir problem. Çeşitli yaklaşımlar yapabilirsiniz ama başarı konusunda bir şey diyemem. 
- Sözlüğü özel bir veri yapısına koyup sadece ön kısmı uyan kelimeler için de sonuç gösterebilirsiniz.
- Zemberek türü bir uygulama ile arama terimlerinin kök-gövde hallerini bulup bunları sözlüğünüzde arayabilirsiniz. Ama bu Osmanlıca olduğu için sözlük kelimelerinin zemberek'e eklenmesi gerekebilir. Bunu sistemin ilklendirilmesi sırasında yapabiliyorsunuz. Zahmetli bir iş. 

Bu konu proje ile ilgili olmadığı için kapatıyorum.

**Comment by nexaas** [comment]
teşekkürler
