### ISSUE TITLE
How to run with MATLAB?

### ISSUE THREAD

**Issue by mozcalici** [ahmetaa/zemberek-nlp#197]
It would be very helpful to provide a guideline to call these functions within MATLAB

**Comment by ahmetaa** [comment]
If Matlab can call Java functions, you may try it with the project jar file. However we do not plan to test or document this. If you make it work, please let us know how so we can put it in the wiki.

**Comment by ahmetaa** [comment]
https://www.mathworks.com/help/matlab/using-java-libraries-in-matlab.html may help
