### ISSUE TITLE
TurkishSentenceParser.preProcess splits string at foreign character

### ISSUE THREAD

**Issue by faraday** [ahmetaa/zemberek-nlp#20]
TurkishLexer provides ends a token when it encounters a foreign character. For a foreign string, this makes it yield multiple tokens for a simple foreign string (simple: containing no separators).

This _might_ not be considered bad behavior at Lexer level.

However, TurkishSentenceParser.preProcess joins these tokens by printing space between them. This leads to such examples:

André -> [Andr, é]
Bjørn -> [Bj, ø, rn]

etc. after preprocessing

**Comment by ahmetaa** [comment]
This is addressed in 0.12.0 But word "L'Oréal" still fails as it contains an apostrophe. I will create a separate issue for it.
