### ISSUE TITLE
Cannot find reference item id

### ISSUE THREAD

**Issue by ozturkberkay** [ahmetaa/zemberek-nlp#202]
I was trying to create a `TurkishMorphology` object using a custom dictionary. If I only add the root abbreviation to the lexicon, it works properly. However, if I add other pronunciations referring to the root, it gives me an error:

**test-lexicon.txt:**
```
VST [P:Noun, Abbrv; Pr:viesti]
VST [Pr:vesete; Ref:VST; Index:2]
NAMD [P:Noun, Abbrv; Pr:enemdi]
NAMD [Pr:neamede; Ref:NAMD; Index:2]
NAMD [Pr:namde; Ref:NAMD; Index:3]
```

**standard_morphology.py:**
```python
lexicon = RootLexicon.builder().setLexicon(RootLexicon.DEFAULT).addTextDictionaries(Paths.get('../../../data/dictionaries/test-lexicon.txt')).build()
morphology = TurkishMorphology.create(lexicon)
```

**Terminal:**
```console
Cannot find reference item id VST_Noun                                                              | TurkishDictionaryLoader$TextLexiconProcessor#getResult
```
By looking at the [source code](https://github.com/ahmetaa/zemberek-nlp/blob/master/morphology/src/main/java/zemberek/morphology/lexicon/tr/TurkishDictionaryLoader.java#L230), it seems like the `DictionaryItem` with the corresponding reference id could not be found inside the `RootLexicon` instance:
```java
          String referenceId = lateEntry.getMetaData(MetaDataId.REF_ID);
          if (!referenceId.contains("_")) {
            referenceId = referenceId + "_Noun";
          }
          DictionaryItem refItem = rootLexicon.getItemById(referenceId);
          if (refItem == null) {
            Log.warn("Cannot find reference item id " + referenceId);
          }
```

Any ideas?

**Comment by ahmetaa** [comment]
If you define it like this:

```
VST [P:Noun, Abbrv; Pr:viesti]
VST [P:Noun, Abbrv; Pr:vesete; Ref:VST_Noun_Abbrv; Index:2]

```
It would probably work. Unfortunately this mechanism is cumbersome.

**Comment by ozturkberkay** [comment]
Thanks! That fixed the problem.
