### ISSUE TITLE
Normalization paths are not available. Normalization service is down. 

### ISSUE THREAD

**Issue by spolat-zz** [ahmetaa/zemberek-nlp#203]

**Comment by ahmetaa** [comment]
Please clarify.

**Comment by spolat-zz** [comment]
Windows ortamında Consolda;

java -jar zemberek-full.jar StartGrpcServer komutu ile v16 çalıştırıyorum ve fakat diğer tüm servisler çalışıyor ama Normalization servisi çalışmıyor ve "Normalization paths are not available. Normalization service is down." mesajını yazıyor konsolda.

Burada bahsedilen path neresi ve orada hangi dosyalar yer almalı ?

**Comment by ahmetaa** [comment]
Bunun için https://github.com/ahmetaa/zemberek-nlp/tree/master/normalization#usage bağlantısındaki dokümana bakın. Normalizasyon için dağıtımda olmayan dosyalara ihtiyacınız var.

**Comment by ahmetaa** [comment]
Ayrıca grpc sunucusunu çalıştırırken --dataRoot ile indirilen veri klasörünü vermeniz gerekir.

**Comment by spolat-zz** [comment]
Proje, paylaşım ve yardımlarınız için teşekkür ederim, yazdığınız gibi yaptım ve gayet güzel çalıştı, Başarılar.
