### ISSUE TITLE
.Proto uzantılı kaynakların çözümlenememesi

### ISSUE THREAD

**Issue by ugrozkr** [ahmetaa/zemberek-nlp#210]
morphology ve grpc kütüphanelerinde referans edilen .proto uzantılı sınıfları görmüyor maalesef çözümlemek için ne yapmak gerekir.

**Comment by mdakin** [comment]
Burada kodu nasil derlemeniz gerektigi anlatiliyor:
https://github.com/ahmetaa/zemberek-nlp/wiki/Zemberek-For-Developers

**Comment by ugrozkr** [comment]
> @ugrozkr
> Burada kodu nasil derlemeniz gerektigi anlatiliyor:
> https://github.com/ahmetaa/zemberek-nlp/wiki/Zemberek-For-Developers

Teşekkürler oldukça pratik oldu.
