### ISSUE TITLE
ner test resources

### ISSUE THREAD

**Issue by ugrozkr** [ahmetaa/zemberek-nlp#213]
How can i found ner test resources ? For example: ner-train, ner-test, my-model files ? I want to analyze format and type of documents ?

**Comment by ugrozkr** [comment]
UseNer.java sınıfı için örnek dosya adı, path ve input için tek satır kayıt örneği verebilir misiniz ?

**Comment by yusufcakmakk** [comment]
Projenin gerekli modülünde ilgili açıklamalar mevcut.
https://github.com/ahmetaa/zemberek-nlp/blob/master/ner/README.md

**Comment by ahmetaa** [comment]
Size bir örnek hazırlamaya çalışacağım. Ama zaman alabilir.

**Comment by ugrozkr** [comment]
çok teşekkür ederim bekliyor olacağım. @ahmetaa

**Comment by ugrozkr** [comment]
@ahmetaa bey NER ile ilgili örneği tahmini ne zaman paylaşabilirsiniz, ona göre takvimlendirme yapıyoruz. bu arada kod tarafını yazmanıza gerek yok bizim elimizde örnek input modelleri yok formatları konusunda desteğe ihtiyacımız var örnek 2 model dosyası iletseniz mantığını görmek için yeterli olur bizim için.

**Comment by ahmetaa** [comment]
Bu konuda maalesef size söz veremem. Bu ara işlerim çok yoğunlaştı. Her halükarda iş süreçlerinizi buna bağlamamanızı öneririm. Bunun yerine şöyle yapabilirsiniz, şurada bir veri seti var bunu kullanıp deneyin. Ancak bu set her tür kullanım için uygun mudur bilmiyorum, sorumluluk sizin:

http://haydut.isikun.edu.tr/nlptoolkit.html

ner corpusunu indirin ve bir parçasını test olarak ayırın. Annotation türü olarak ENAMEX seçin. Sonra eğitip deneyin.

**Comment by ahmetaa** [comment]
Eğitimi TrainNerModel komut satırı uygulaması ile de yapabilirsiniz.

**Comment by ugrozkr** [comment]
indirdiğim dosyada sadece ner.txt veri dosyası mevcut apps modülü bulunmuyor. @ahmetaa

**Comment by ahmetaa** [comment]
apps modülü zemberek içerisindeki bir modül. komut satırı uygulamaları var. Siz isterseniz https://github.com/ahmetaa/zemberek-nlp/tree/master/ner buradaki yolu izleyin.
