### ISSUE TITLE
I had problems while adding zemberek as maven dependency and repository

### ISSUE THREAD

**Issue by ekingunoncu** [ahmetaa/zemberek-nlp#216]
Hi!
Firstly, thank you for this great job! 
I don't know that if I implemented something wrong but when I try to add zemberek project using maven I could not import some packages such as normalization due to that I could not use TurkishSpellChecker.

I am using IntelliJ and I added these two properly to my pom.xml: 
```
<repositories>
    <repository>
        <id>zemberek-repo</id>
        <name>zemberek Maven Repo on Github</name>
        <url>https://raw.github.com/ahmetaa/maven-repo/master</url>
    </repository>
</repositories>
<dependencies>
    <dependency>
        <groupId>zemberek-nlp</groupId>
        <artifactId>zemberek-morphology</artifactId>
        <version>0.16.0</version>
    </dependency>
</dependencies>

```
Everything seems fine when I download jar from google drive and add it manually.
Now it is working but I just wanted to let you know about the issue that I had as a feedback.

**Comment by ahmetaa** [comment]
Try adding zemberek-normalization module dependency.

**Comment by ahmetaa** [comment]
I am closing this issue. Reopen if problem persists.
