### ISSUE TITLE
Cannot parse the word: resime

### ISSUE THREAD

**Issue by faraday** [ahmetaa/zemberek-nlp#22]
Even though the word __resim__ (picture) can be parsed as:
```
[(resim:resim) (Noun;A3sg+Pnon+Nom)]
```

__resime__, which should have been parsed as:
```
[(resim:resim) (Noun;A3sg+Pnon+Dat:e)]
```

cannot be parsed, resulting in:
```
[(UNK:resime) (Unk,Unk;Unkown)]
```

**Comment by ahmetaa** [comment]
Even though dropping the last vowel is not optional for this word, this kind of additions can be made for practical reasons. But adding a second `resim` causes the problem of duplicated parse results (`resimlerde` would have two identical looking parses). I will look into this and try to find a good solution.

**Comment by ahmetaa** [comment]
I am marking this as as-intended. You can add a new dictionary item for such words as a workaround.
Such as
    resim [A:Ext; Index:1 ; Ref:resim]
or directly 
   resim
