### ISSUE TITLE
gRPC Server başlatma hatası

### ISSUE THREAD

**Issue by spolat-dev** [ahmetaa/zemberek-nlp#221]
komut satırında, "java -jar zemberek-full.jar StartGrpcServer" komutuyla başlatmak istediğimde
"no main manifest attribute, in zemberek-full.jar" hatası alıyorum.

**Comment by ahmetaa** [comment]
Buna bakacagim, gecici olarak `java -cp zemberek-full.jar zemberek.apps.grpc.StartGrpcServer` seklinde deneyebilir misiniz?

**Comment by spolat-dev** [comment]
Yazdığınız şekilde alttaki hatayı alıyorum ve server başlatılamıyor:

_zem.io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional server found. Try adding a dependency on the grpc-netty or grpc-netty-shaded artifact
        at _zem.io.grpc.ServerProvider.provider(ServerProvider.java:55)
        at _zem.io.grpc.ServerBuilder.forPort(ServerBuilder.java:41)
        at zemberek.grpc.server.ZemberekGrpcServer.start(ZemberekGrpcServer.java:28)
        at zemberek.apps.grpc.StartGrpcServer.run(StartGrpcServer.java:36)
        at zemberek.apps.ConsoleApp.execute(ConsoleApp.java:18)
        at zemberek.apps.grpc.StartGrpcServer.main(StartGrpcServer.java:40)

**Comment by ahmetaa** [comment]
Trunk icerisinde bu duzeldi, Bu hafta sonuna kadar bir bugfix release cikarmaya calisacagim.

**Comment by spolat-dev** [comment]
Merhaba, sorunun giderilmesi için (bugfix ver.) bir takvim var mı acaba?

**Comment by mezig351** [comment]
Merhaba, ben aynı problemi zemberek-full.jar ile yeni yaşadım, versiyon 17'den 16'ya geçmek benim için verimli oldu.

**Comment by esrshn** [comment]
Merhabalar,
Asagida ki hata ile ilgili yardimlarinizi rica ediyorum.

Versiyon 17 kullanilmaktadir.
![grpc-server-error](https://user-images.githubusercontent.com/4234798/59696169-288eb680-91f4-11e9-9ad4-1db9e52e0f08.png)

**Comment by spolat-dev** [comment]
Merhaba, v17.1 de gRPC Server başlatma hatası düzeltilmiş, uğraşlarınız için teşekkür ederiz.

**Comment by murat1309** [comment]
Merhaba zemberek'i grpc server olarak ayağa kaldırmak istiyorum. grpc server projesini çalıştırmam yeterli mi yoksa tüm zemberek-nlp modüllerine ihtiyaç var mı ?
