### ISSUE TITLE
Rendezvous Hatası

### ISSUE THREAD

**Issue by brcsnt** [ahmetaa/zemberek-nlp#229]
Merhaba, kodu çalıştırdığım zaman tokenize adımında hata alıyor.
Yardımcı olabilir misiniz?
Teşekkürler.

  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)

  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)

_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1568321744.512000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3818,"referenced_errors":[{"created":"@1568321744.512000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
>

**Comment by ahmetaa** [comment]
problem halen devam ediyor mu?

**Comment by brcsnt** [comment]
Merhaba, evet hala aynı hatayı alıyorum.
zemberek_client_test.py scriptini çalıştırıyorum.
Teşekkürler.

**Comment by brcsnt** [comment]
Merhaba bu hatayı geçtim. 

Normalization paths are not available. Normalization service is down.                               | NormalizationServiceImpl#<init>

bu kısımda hata alıyorum. Yardımcı olabilir misiniz?

**Comment by ahmetaa** [comment]
Bunun icin dokumanda belirtilen (https://github.com/ahmetaa/zemberek-nlp/tree/master/normalization#usage) dosyayi indirip bir yere acmaniz ve serveri calistirirken bu diziniparametre olarak vermeniz gerekiyor.

Mesela

`java -jar zemberek-full.jar StartGrpcServer --dataRoot /home/aaa/zemberek-data
`

**Comment by brcsnt** [comment]
Merhaba, hatayı geçtim. Yardımlarınız için teşekkür ederim.
