### ISSUE TITLE
Cannot parse the word: birbirleri

### ISSUE THREAD

**Issue by faraday** [ahmetaa/zemberek-nlp#23]
Even though **birbiri** can be parsed as:

```
[(birbiri:birbiri) (Pron,Quant;A3sg+Pnon+Nom)]
```

**birbirleri**, which could have been parsed as:

```
Pron birbirleri Pron+Quant+A3pl+P3pl+Nom
```

remains unknown by the parser.

**Comment by ahmetaa** [comment]
This is addressed in 0.12.0

[birbiri:Pron,Quant] birbir:Pron+A3pl+leri:P3pl
