### ISSUE TITLE
SentenceBoundryDetection'da bütün bir txt okumak

### ISSUE THREAD

**Issue by alihannka** [ahmetaa/zemberek-nlp#231]
SentenceBoundryDetection'da  extractor.from derken txt dosyasını vererek direkt okuma işlemini nasıl sağlayabiliriz ? Direkt txt okumak için bir komut var mı acaba?

**Comment by ahmetaa** [comment]
Boyle bir komut yok. Ama soyle bir kod yazabilirsiniz:

```
        TurkishSentenceExtractor.DEFAULT.fromParagraphs(
                Files.readAllLines(Paths.get("foo.txt"), StandardCharsets.UTF_8));
```

**Comment by alihannka** [comment]
Bütün emeğiniz ve geri dönüşünüz için teşekkür ederim

**Comment by ahmetaa** [comment]
Rica ederim. Kolay gelsin.
