### ISSUE TITLE
NER Hatası

### ISSUE THREAD

**Issue by Miracle00** [ahmetaa/zemberek-nlp#244]
Merhaba,
şöyle bir hata aldım ve çözemedim. 

![Ekran Alıntısı2](https://user-images.githubusercontent.com/28346984/79099741-82f19880-7d6d-11ea-9561-5bf42efb16bb.PNG)

**Comment by yusufcakmakk** [comment]
Merhaba,
Bu problemle bende karşılaşmıştım. Tam olarak neyin sebep olduğunu anlayamadım fakat çözüm olarak şunu deneyebilirsiniz:
zemberek.core.data.Weights sınıfında 48. satırda bulunan kodu
`float weight = Float.parseFloat(Strings.subStringUntilFirst(s, " "));`
replace metodunu kullanarak "," değerini "." ile değiştirebilirsin
`float weight = Float.parseFloat(Strings.subStringUntilFirst(s, " ").replace(',','.'));`
Ayrıca şurayı inceleyebilirsin
[https://www.java67.com/2016/10/10-reasons-of-javalangnumberformatexception-in-java-solution.html](url)

**Comment by Miracle00** [comment]
@yusufcakmakk  Ben bu değişikliğin nasıl yapılacığını tam bilmiyorum. Belirttiğiniz değişiklikler model uzantılı dosyalardaki  "0,05" gibi değerleri  "0.05" gibi olmasını mı sağlayacak ?

**Comment by yusufcakmakk** [comment]
@Miracle00 zemberek-core modülünü indirip içerisinde belirttiğim değişikliği yaptıktan sonra build(compile install gibi) yapabilirsiniz.
Evet dosyadan okuma esnasında eğer dosyada virgül olarak kalmışsa noktaya çevirecek.
Eğer bu buil işlemini yapmak istemiyorsanız model dosyası içerisinde bulunan ağırlıkların içinde virgüller varsa noktalara çevirip deneyebilirsin.

**Comment by Miracle00** [comment]
@yusufcakmakk virgülleri noktalara çevirip denedim sorunsuz çalıştı. Yardımlarınız için çok teşekkür ederim. İyi çalışmalar.

**Comment by yusufcakmakk** [comment]
@Miracle00 rica ederim kolay gelsin. Konuyu kapatabilirsiniz
