### ISSUE TITLE
Cümleyi öğelerine ayırma

### ISSUE THREAD

**Issue by hasnhasan** [ahmetaa/zemberek-nlp#260]
Cümleleri öğelerine ayırmak istiyorum. Bir türlü bunu başaramadım. Hep bir karışıklık çıkıyor. Bir cümlede doğru şeklde çözümlenirken diğer cümlede yanlış oluyor.
Bu konuda  nasıl bir yol izlememiz gerekir ?

**Comment by ahmetaa** [comment]
Bu kolay bir problem degil. Zemberek dogrudan bu konuda bir fonksiyon saglamiyor. Bunun icin makine ogrenmesi yontemleri kullanarak kisitli basari saglanabilir. Ama elinizde bol miktardaa egitim verisi olmasi gerekir. Dependency parsing konusuna da bakabilirisniz. 
Stanford Stanzaya goz atabilirsiniz ( https://stanfordnlp.github.io/stanza/ )
