### ISSUE TITLE
Noun Phrase Extraction

### ISSUE THREAD

**Issue by okanvk** [ahmetaa/zemberek-nlp#262]
Merhaba, zemberek içerisinde bir noun phrase extraction çalışması bulunuyor mu?

Bir örnek şu olabilir,

Mustafa Kemal Atatürk ankaraya gitti. -> (Mustafa Kemal Atatürk)
Büyük araba park etti. -> (Büyük araba)

**Comment by ahmetaa** [comment]
Hayir.  Bir ara kismen bu ihtiyaci karsilayacak unsupervised key phrase extraction kodu ekleme konusunda calisma yapmistim ama gerisi gelmemisti. (https://github.com/ahmetaa/zemberek-nlp/blob/master/experiment/src/main/java/zemberek/keyphrase/UnsupervisedKeyPhraseExtractor.java)

Bu konuda belki Turkce icin iyi calisan bir depdency parser uzereinden de cikarim yapabilirisniz (Zemberekte mevcut degil).
