### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by selam** [ahmetaa/zemberek-nlp#27]
Bir kaç wiki sayfası hazırlasan ne güzel olur, proje ne durumda eski zemberek kütüphanesine ne oldu,   Lucene, Solr, Elasticsearch ile birlikte kullanabiliyormuyuz yoksa snowball'dan mı devam edeceğiz, sistem kütüphanelerimizi yenileyelim mi? libreoffice vb. uygulamaların zemberek köprüleri güncellensin mi?  Neden eski kod ile bu yeni kod birbirinden bu kadar uzak?

Bunları biraz anlatsan ne güzel olur

**Comment by ahmetaa** [comment]
İki sene sonra bir şeyler yazdım :) 
https://github.com/ahmetaa/zemberek-nlp/wiki

**Comment by iorixxx** [comment]
Wiki'nin `What about Libre Office or Lucene-Solr extensions?` kısmına benim projeme link vermeniz mümkün olur mu acaba?
https://github.com/iorixxx/lucene-solr-analysis-turkish

**Comment by ahmetaa** [comment]
@iorixxx tabi.
