### ISSUE TITLE
Python usage

### ISSUE THREAD

**Issue by DuyguA** [ahmetaa/zemberek-nlp#29]
Hello,
I'd like to ask if it's possible to use zemberek-nlp in Python?

**Comment by mdakin** [comment]
Maybe you can have a look at Ali Ok's TRNLTK library?
https://github.com/aliok/trnltk

**Comment by ahmetaa** [comment]
Unfortunately not. Our intention in the beginning was to make system usable by other languages by serializing the search graph, but it seems like that it requires substantial work. Maybe in the future. But I will close this issue now.
