### ISSUE TITLE
Garib bir tokenization and stem problemi 

### ISSUE THREAD

**Issue by volkanagun** [ahmetaa/zemberek-nlp#30]
"Pirinç Kasım ayına göre 86, kuşbaşı et 9, beyazpeynir 16, yoğurt 11, bal 10 kuruş arttı."

Best parse uygulandığında sonuçta sadece stem'leri aldığımızda
86 --> 16 olarak çevrilmiş oluyor. Ancak aşağıdaki cümlede bir sorun yok

"86 lira harcardım."

**Comment by ahmetaa** [comment]
Bu hatayı ortaya çıkaramadım. Kullandığım kod (0.9.1):

        TurkishWordParserGenerator morphParser = TurkishWordParserGenerator.createWithDefaults();
        Z3MarkovModelDisambiguator disambiguator = new Z3MarkovModelDisambiguator();
        TurkishSentenceParser sentenceParser = new TurkishSentenceParser(
                morphParser,
                disambiguator
        );
        List<MorphParse> res = sentenceParser.bestParse("86 lira harcardım.");
        for (MorphParse re : res) {
            System.out.println(re);
        }  

Çıktı:

[(86:86) (Num,Card)]
[(lira:lira) (Noun;A3sg+Pnon+Nom)]
[(harcamak:harca) (Verb;Pos)(Adj;AorPart:r)(Noun;A3sg+Pnon+Nom)(Verb;Past:dı+A1sg:m)]
[(.:.) (Punc)]

**Comment by ahmetaa** [comment]
Bu belirsizlik gidericideki bir hatadan kaynaklanıyor. Bakıyorum.

**Comment by ahmetaa** [comment]
Fixed in trunk
