### ISSUE TITLE
Duplicate Solution for word "kedimsi"

### ISSUE THREAD

**Issue by hrzafer** [ahmetaa/zemberek-nlp#31]
Word = kedimsi
[(kedi:kedi) (Noun;A3sg+Pnon+Nom)(Adj;JustLike:msi)]
[(kedi:kedi) (Noun;A3sg+Pnon+Nom)(Adj;JustLike:msi)]

**Comment by ahmetaa** [comment]
Correct. There was a duplication in TurkishSuffixes. Will be fixed in new version.

**Comment by ahmetaa** [comment]
Fixed in trunk
