### ISSUE TITLE
No solution for "(onlar) kitaplar"

### ISSUE THREAD

**Issue by hrzafer** [ahmetaa/zemberek-nlp#33]
Word = kitaplar
[(kitap:kitap) (Noun;A3pl:lar+Pnon+Nom)]

A solution like

kedi+Noun+A3sg+Pnon+Nom^DB+Verb+Zero+Pres+A3pl

is missing.

**Comment by ahmetaa** [comment]
We deliberately skip the second type parse for severe ambiguity problems.
