### ISSUE TITLE
How can we use this with c# ?

### ISSUE THREAD

**Issue by MonsterMMORPG** [ahmetaa/zemberek-nlp#35]
How can we use this with c# ?

Any tutorial documentation for latest zemberek?

**Comment by ahmetaa** [comment]
You cannot use it with C# directly. However perhaps you can give a try to NZemberek (not developed anymore).

**Comment by MonsterMMORPG** [comment]
Ty for reply aren't there any wrapper for this? Also did you shut down web service api as well? i can't find anywhere to test out.

Actually i am planning to use word correction feature alone for incorrectly typed words.

That NZemberek is 2007 extremely outdated

**Comment by ahmetaa** [comment]
No there is no wrapper or web service.
For word correction, I suggest dictionary based systems. There is a rather old but kinda useful Turkish hun-spell dictionary ( https://code.google.com/p/tr-spell/ ) you can try. However, inflectional nature of Turkish become troublesome and this dictioanry may not contain many correct words. But nevertheless even Google Chrome uses it. There is also an error tolerant word finding mechanism that can be used if you happen to have a large number of Turkish words https://github.com/ahmetaa/leblebi with only one class with some dependencies.  Recently I intended to write an uber spell checker but too much dreams too little time.

**Comment by MonsterMMORPG** [comment]
Ty very much again for reply. From your answer you suggest me this am i right?

First i check my word whether exists in any of those dictionaries or not. If exists continue

If not exists, I use a string distance algorithm and calculate its distance with every word in that dictionary (pretty resources using) and chose its closest distance (most similar) one am i right?

That is also what Zemberek does?

**Comment by ahmetaa** [comment]
Zemberek does not provide this services.
You should write some code at the end. Also checking each words distance would be prohibitively slow. 
if you use https://github.com/ahmetaa/leblebi it can do that operation very fast. but again, this is a Java application. There must be myriad of .Net projects doing that fast using another algorithms such as Peter Norvig's (http://norvig.com/spell-correct.html). Also look for Hunspell .net integration.

**Comment by MonsterMMORPG** [comment]
Ty very much reply again. Certainly i can optimize speed. But the general idea is this way right? Also i thought zemberek has correct word return feature? Which checks incorrectly spelled words?
