### ISSUE TITLE
zemberek.kelimeDenetle(str) ve cumlenin Turkce olup olmadiginin test edilmesi

### ISSUE THREAD

**Issue by atahanozer** [ahmetaa/zemberek-nlp#45]
Eski versiyonlarda "zemberek.kelimeDenetle(str)" seklinde calisan, yanlis yazilmis kelimelere duzeltme onerisi fonksiyonu ve verilen cumlenin Turkce olup olmadigini test eden fonksiyona nasil erisebiliriz?
Dokumantasyonda ve ornek kodlarda bulamadik.

**Comment by ahmetaa** [comment]
zemberek-nlp projesinde henüz öneri özelliği ve dil test özelliği yok. 

Ancak alternatif olarak 
- Bir derlemden zemberek ile doğru kelimeleri elde edip girilen bir kelimenin bunlardan yakın olanlarını bulan bir uygulama ile kullanabilirsiniz. (Örneğin https://github.com/ahmetaa/leblebi gibi.)
- Dil testi için https://github.com/optimaize/language-detector ya da zemberek-nlp kullanan https://github.com/ahmetaa/lang-id ya da  kullanabilirsiniz.

**Comment by ahmetaa** [comment]
Bu soruları FAQ'ya ekledim.

**Comment by atahanozer** [comment]
Tesekkurler

**Comment by ahmetaa** [comment]
Her iki özellik de 0.11.0 sürümünde yer alacak.
