### ISSUE TITLE
Zemberek Extension for LibreOffice is Not Updated since 2011

### ISSUE THREAD

**Issue by damascene** [ahmetaa/zemberek-nlp#48]
Zemberek Extension for LibreOffice is Not Updated since 2011

http://extensions.libreoffice.org/extension-center/zemberek-turkce-yazim-denetleyicisi

Could you please work on it?

**Comment by ahmetaa** [comment]
Please refer to FAQ in wiki for this.
Unfortunately I do not have much spare time, maybe one day.
