### ISSUE TITLE
sözlüğe özel isim eklemek

### ISSUE THREAD

**Issue by udoga** [ahmetaa/zemberek-nlp#49]
Merhaba,
[Buradaki](https://github.com/ahmetaa/turkish-nlp-examples/blob/master/src/main/java/morphology/AddNewDictionaryItem.java) örnekte, sözlükte olan bir sözcüğün özel isim halini ekleyemedim. Örneğin "Meydan" sözcüğü:
`new DictionaryItem("Meydan", "meydan", "meydan", PrimaryPos.Noun, SecondaryPos.ProperNoun)`
şeklinde özel isim olarak eklenemiyor. Nasıl çözülebilir acaba?

**Comment by ahmetaa** [comment]
Merhaba,
Problemi bulmak için epey çaba gösterdim. Bunun nedeni biraz karışık. Şu şekilde:

Sistem kendisine büyük harfle başlayan ya da küçük harfle başlayan ama kesme içeren bir kelime yollandığında eli boş dönmemek için dinamik olarak yapay bir özel ad kökünü otomatik olarak oluşturabiliyor. Buraya kadar aslında bir sorun yok çünkü bu yapay kök arama grafına eklenmiyor. Elde edilen parse sonucundaki DictionaryItem  nesnesinin rootAttributes setinde RootAttribute.Runtime şeklinde bir bilgi yer alıyor. Yani bu kökün çalışma sırasında otomatik olarak üretildiğinin anlaşılması için. 

Ancak, sonuçlar dinamik bir Cache yapısına koyulduğundan, yeni kökü eklemeden önce aynı isimle bir parse işlemi yapılmışsa yapılan parse işlemi sonrasındaki sonuçlar Cache içerisine yazıldığından yeniden parse etmeye uğraşmadan doğrudan sonuç dönüyor. 

uzun lafın kısası, yeni kökleri eklemeden önce  TurkishWordParserGenerator sınıfında ait nesnenizde invalidateAllCache(); çağırmanız gerekiyor. Sonraki sürümde sistemin çaktırmadan olmayan kelimeler için kök üretmesini engelleyip kullanıcının bunu isterse yapmasını sağlamayı düşünüyorum. Bu şekilde beklenmedik sonuçların ortaya çıkması harhalde bir nebze engellenir. Bunun için ayrıca bir issue açacağım.

**Comment by ahmetaa** [comment]
invalidateCache(String) de aslında işe yarayabilirdi ancak bir hatadan dolayı cep içerisinde anahtar olarak girişin ham halini değil normalize edilmiş halini tutuyorum. Bunu da düzelteceğim.

**Comment by ahmetaa** [comment]
Nlp-examples projesine ilgili kod örneklerini ekledim. Güncelleyip bakabilirsiniz
