### ISSUE TITLE
Tireleme fonksiyonu

### ISSUE THREAD

**Issue by th0mass** [ahmetaa/zemberek-nlp#50]
Merhaba hyph_tr_TR.dic isimli tireleme dosyasını nerede bulabilirim? Sanırım openoffice eklentisi içinde olmalı imiş ama baktığımda içinde bulamadım. Yardımcı olursanız sevinirim, Kolay gelsin.

**Comment by th0mass** [comment]
Adobre illustrator içinde buldum ama varsa açık kaynak bir tane daha uygun olacak.

**Comment by ahmetaa** [comment]
Bahsettiğiniz dosya bu proje ile ilgili değil. Belki şu bağlantı işinize yarayabilir.
http://forum.libreoffice.org.tr/viewtopic.php?t=920&p=1837

**Comment by th0mass** [comment]
evet yaklaşık aynı dosya, teşekkürler
