### ISSUE TITLE
Zemberek cannot parse `resmî [P:Adj]`

### ISSUE THREAD

**Issue by sonerx** [ahmetaa/zemberek-nlp#78]
resmî [P:Adj] is in master dictionary but Zemberek cannot process it.

**Comment by ahmetaa** [comment]
This can probably parsed with Sentence analyzer. Because word analyzer does not apply circumflex normalization to input. I will consider including a more detailed normalizer in word analyzer. But in reality most applications works with sentences, not words.

**Comment by ahmetaa** [comment]
This is fixed in 0.12.0
