### ISSUE TITLE
How we can use this in node.js environment?

### ISSUE THREAD

**Issue by berkaey** [ahmetaa/zemberek-nlp#80]
Hey there,

I'm looking for a solution or guideline for either port or create some submodule to use it in a JS Application. 

So where to start?

PS: Probably I will start/need first the "Suggest word" feature. (to optimise a search engine)

btw Great Work, a.k.a "Alkış ;)"

**Comment by ahmetaa** [comment]
Hi,

I think only sensible way of using it in a node.js environment is to develop a java based server (rest , grpc vs) and access it from a client. 
I do not suggest porting code much. Zemberek code is not so clean in places, hopefully I will tackle some complexity in versions 0.11.0 and 0.12.0
Also please check out the alternatives such as open-nlp and alike. 

Thanks
