### ISSUE TITLE
Zemberek cannot process `şunları diyerek email birisi`

### ISSUE THREAD

**Issue by sonerx** [ahmetaa/zemberek-nlp#82]
I just want to inform unrecognized tokens. Sorry if they are reported before

**Comment by ahmetaa** [comment]
Thanks. I knew them but it is good that they are reported here.

**Comment by ahmetaa** [comment]
All except email is addressed. Closing. I will add email issue separately. 
şunları
[şu:Pron,Demons] şu:Pron+nlar:A3pl+ı:Acc
diyerek
[demek:Verb] di:Verb|yerek:ByDoingSo→Adv
birisi
[biri:Pron,Quant] biri:Pron+A3sg+si:P3sg
