### ISSUE TITLE
Problem while creating a .dll file from zemberek-all-0.10.0.jar

### ISSUE THREAD

**Issue by ardarslan** [ahmetaa/zemberek-nlp#92]
Hello,

First, I'd like to thank you so much for these precious works. Since I'm working on a .NET project, I converted zemberek-all-0.10.0.jar file to a .dll file using IKVM.net. I added zemberek-all-0.10.0.dll, and necessary IKVM .dll files as references to my project. However Visual Studio 2015 did not see any classes that are in the project. I cannot even import "zemberek-all-0.10.0.dll" file into my project by the "using" term. Can someone post a working .dll file for the version 0.10.0?

Best,

Arda

**Comment by ardarslan** [comment]
Well, I created a zemberek.jar by using Maven. I used a plugin to make this .jar file include its dependencies. However after creation, this .jar file's size was 7359 KB. I think I failed adding some of its dependencies while creating this .jar file. Could you please tell me how did you exported the zemberek-all-0.10.0.jar file with a size of 12884 KB?

Best,

Arda

**Comment by ardarslan** [comment]
Please ignore my previous questions. I managed to create zemberek-all-0.10.0.jar file which is exactly the same with the file that you shared in distributions folder. My ultimate question is as follows: Does zemberek-all-0.10.0.jar file include all of its dependencies? Or do I also need other .jar files that you shared in "dependencies" and "module-jars" folders to use Zemberek?

**Comment by ahmetaa** [comment]
zemberek-all-0.10.0.jar contains only the ones in the module-jars. You will need jar in dependencies folder if you need to deploy it. If you want to create single jar with all dependencies, there are several ways of doing it. 
1- Copy related dependency lines from main pom.xml to all/dependency-reduced-pom.xml files and re-generate the zemberek-all-0.10.0.jar file. (it will appear in all/target)
2- Search for how to do this in maven in internet.
3- use ant and jarjar or proguard to generate a fat-jar
