### ISSUE TITLE
Add deprecation notice to old zemberek project

### ISSUE THREAD

**Issue by mdakin** [ahmetaa/zemberek-nlp#97]
Right now there is nothing on the github page and creates confusion. It should point to new zemberek project, and we should probably explain the differences and how to have same functionality.

**Comment by ahmetaa** [comment]
I added a readme to https://github.com/ahmetaa/zemberek 
Also made a blog post entry to now unused zemberek-nlp blog
http://zembereknlp.blogspot.com.tr/2017/02/2017-ve-eski-koda-veda.html

I think for showing code and usage differences, more time is required.

**Comment by ahmetaa** [comment]
Also changed zemberek-nlp readme.md for emphasis.
