### ISSUE TITLE
Should TurkishMorphology.analyze return empty list for unknown words?

### ISSUE THREAD

**Issue by ahmetaa** [ahmetaa/zemberek-nlp#98]
Currently we always return a list. And if word is unknown 
- list has only 1 item
- it contains a special UNKNOWN DictionaryItem 

This may be confusing for new users. Should we instead return an empty list?

**Comment by ahmetaa** [comment]
There is another issue about this. Instead of returning List<WordAnalysis> should we return a wrapper object like WordAnalysisResult that also contain the raw and normalised input information. WordAnalysis class has its own issues (Like containing too much rarely used information IGs etc), but that is another discussion.

@mdakin

**Comment by mdakin** [comment]
I am not sure, Returning WorldAnalysisResult sounds allright, but I should use zemberek more to have a better feeling of it :)

**Comment by ahmetaa** [comment]
0.12.0 addresses this.
